version: "2"

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    networks:
      - web
    ports:
      - 80:80
      - 443:443
      - 9080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  web:
    external: true
